export const AuditAction = {
  TICKET_VOIDED: 'TICKET_VOIDED',
  COMMISSION_RULE_CHANGED: 'COMMISSION_RULE_CHANGED',
  SETTING_CHANGED: 'SETTING_CHANGED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  CASH_REGISTER_CLOSED: 'CASH_REGISTER_CLOSED',
  LOYALTY_REDEEMED: 'LOYALTY_REDEEMED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
